spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/careplus
    username: careplus
    password: careplus
  flyway:
    locations: classpath:db/migration,classpath:db/seed
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    ma.careplus: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
